---
version: 1

name: prometheus-nrpe-exporter
description: Prometheus exporter for NRPE
homepage: https://github.com/RobustPerception/nrpe_exporter

maintainer: Recipes Maintainers <recipes@mkdeb.sh>

source:
  url: https://github.com/RobustPerception/nrpe_exporter/releases/download/{{ .Version }}/nrpe_exporter-{{ .Version }}.linux-{{ .Arch }}.tar.gz
  strip: 1
  arch-mapping:
    amd64: amd64
    arm64: arm64
    armel: armv6
    armhf: armv7
    i386: "386"

control:
  depends:
  - adduser
  - daemon
  - libc6
  description: |
    The NRPE exporter exposes metrics on commands sent to a running NRPE
    daemon.
  section: net

install:
  recipe:
    /etc/default:
    - pattern: default
      rename: prometheus-nrpe-exporter
      conffile: true
    /etc/init.d:
    - pattern: init
      rename: prometheus-nrpe-exporter
      conffile: true
  upstream:
    /usr/bin:
    - pattern: nrpe_exporter
      rename: prometheus-nrpe-exporter

dirs:
- /var/lib/prometheus/nrpe-exporter
- /var/log/prometheus

# vim: ts=2 sw=2 et
