---
version: 1

name: prometheus
description: monitoring system and time series database
homepage: https://prometheus.io/

maintainer: Recipes Maintainers <recipes@mkdeb.sh>

source:
  url: https://github.com/prometheus/prometheus/releases/download/v{{ .Version }}/prometheus-{{ .Version }}.linux-{{ .Arch }}.tar.gz
  strip: 1
  arch-mapping:
    amd64: amd64
    arm64: arm64
    armel: armv6
    armhf: armv7
    i386: "386"

control:
  depends:
  - adduser
  - daemon
  - libc6
  description: |
    Prometheus is a systems and service monitoring system. It collects metrics
    from configured targets at given intervals, evaluates rule expressions,
    displays the results, and can trigger alerts if some condition is observed
    to be true.

    Prometheus' main distinguishing features as compared to other monitoring
    systems are:

     * a multi-dimensional data model (timeseries defined by metric name and
       set of key/value dimensions)
     * a flexible query language to leverage this dimensionality
     * no dependency on distributed storage; single server nodes are autonomous
     * timeseries collection happens via a pull model over HTTP
     * pushing timeseries is supported via an intermediary gateway
     * targets are discovered via service discovery or static configuration
     * multiple modes of graphing and dashboarding support
     * support for hierarchical and horizontal federation
  section: net

install:
  recipe:
    /etc/default:
    - pattern: default
      rename: prometheus
      conffile: true
    /etc/init.d:
    - pattern: init
      rename: prometheus
      conffile: true
  upstream:
    /etc/prometheus:
    - pattern: prometheus.yml
      conffile: true
    /usr/bin:
    - pattern: prometheus
    - pattern: promtool

dirs:
- /var/lib/prometheus
- /var/log/prometheus

# vim: ts=2 sw=2 et
